### ISSUE TITLE
Update to Django 1.8

### ISSUE THREAD

**Issue by cwebber** [OpenTechStrategies/swoptact#30]
Currently the docs don't specify a version of Django, and [Django 1.8 was released on April 1](https://docs.djangoproject.com/en/1.8/releases/1.8/).

The current install docs break:

```
(swoptact)cwebber@earlgrey:~/devel/swoptact$ python manage.py loaddata sample_data.json
/home/cwebber/devel/swoptact/lib/python3.4/importlib/_bootstrap.py:321: RemovedInDjango19Warning: The django.forms.util module has been renamed. Use django.forms.utils instead.
  return f(*args, **kwds)

Traceback (most recent call last):
  File "/home/cwebber/devel/swoptact/lib/python3.4/site-packages/django/db/models/options.py", line 552, in get_field
    return self.fields_map[field_name]
KeyError: 'name'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/cwebber/devel/swoptact/lib/python3.4/site-packages/django/core/serializers/json.py", line 78, in Deserializer
    for obj in PythonDeserializer(objects, **options):
  File "/home/cwebber/devel/swoptact/lib/python3.4/site-packages/django/core/serializers/python.py", line 120, in Deserializer
    field = Model._meta.get_field(field_name)
  File "/home/cwebber/devel/swoptact/lib/python3.4/site-packages/django/db/models/options.py", line 554, in get_field
    raise FieldDoesNotExist('%s has no field named %r' % (self.object_name, field_name))
django.core.exceptions.FieldDoesNotExist: ContentType has no field named 'name'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "manage.py", line 26, in <module>
    execute_from_command_line(sys.argv)
  File "/home/cwebber/devel/swoptact/lib/python3.4/site-packages/django/core/management/__init__.py", line 338, in execute_from_command_line
    utility.execute()
  File "/home/cwebber/devel/swoptact/lib/python3.4/site-packages/django/core/management/__init__.py", line 330, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/cwebber/devel/swoptact/lib/python3.4/site-packages/django/core/management/base.py", line 390, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/cwebber/devel/swoptact/lib/python3.4/site-packages/django/core/management/base.py", line 441, in execute
    output = self.handle(*args, **options)
  File "/home/cwebber/devel/swoptact/lib/python3.4/site-packages/django/core/management/commands/loaddata.py", line 60, in handle
    self.loaddata(fixture_labels)
  File "/home/cwebber/devel/swoptact/lib/python3.4/site-packages/django/core/management/commands/loaddata.py", line 90, in loaddata
    self.load_label(fixture_label)
  File "/home/cwebber/devel/swoptact/lib/python3.4/site-packages/django/core/management/commands/loaddata.py", line 141, in load_label
    for obj in objects:
  File "/home/cwebber/devel/swoptact/lib/python3.4/site-packages/django/core/serializers/json.py", line 84, in Deserializer
    six.reraise(DeserializationError, DeserializationError(e), sys.exc_info()[2])
  File "/home/cwebber/devel/swoptact/lib/python3.4/site-packages/django/utils/six.py", line 658, in reraise
    raise value.with_traceback(tb)
  File "/home/cwebber/devel/swoptact/lib/python3.4/site-packages/django/core/serializers/json.py", line 78, in Deserializer
    for obj in PythonDeserializer(objects, **options):
  File "/home/cwebber/devel/swoptact/lib/python3.4/site-packages/django/core/serializers/python.py", line 120, in Deserializer
    field = Model._meta.get_field(field_name)
  File "/home/cwebber/devel/swoptact/lib/python3.4/site-packages/django/db/models/options.py", line 554, in get_field
    raise FieldDoesNotExist('%s has no field named %r' % (self.object_name, field_name))
django.core.serializers.base.DeserializationError: Problem installing fixture '/home/cwebber/devel/swoptact/swoptact/fixtures/sample_data.json': ContentType has no field named 'name'
```

It looks like this is because ContentType.name [used to be a field, but now it's a method](https://docs.djangoproject.com/en/1.8/ref/contrib/contenttypes/#the-contenttype-model):

> Before Django 1.8, the name property was a real field on the ContentType model.

Fixing this seems probably as easy as removing the 'name' references in the .json file.

**Comment by reb00ter** [comment]
have this problem too, but when applying migration

**Comment by reb00ter** [comment]
https://code.djangoproject.com/ticket/24513

**Comment by cecilia-donnelly** [comment]
Closing because we are already on Django 1.8.  All current installations are using it, and in fact Django 1.7 no longer works.  See #41 for a broader discussion of the problem with the install documentation.
