### ISSUE TITLE
ProgrammingError exception raised on syncdb

### ISSUE THREAD

**Issue by xray7224** [OpenTechStrategies/swoptact#56]
When I was trying to complete #53, I get this exception:
```
Running migrations:
  Rendering model states... DONE
  Applying swoptact.0025_auto_20150424_1026...Traceback (most recent call last):
  File "/var/www/swoptact/lib/python3.4/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
psycopg2.ProgrammingError: column "address_id" cannot be cast automatically to type integer
HINT:  Specify a USING expression to perform the conversion.


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "manage.py", line 26, in <module>
    execute_from_command_line(sys.argv)
  File "/var/www/swoptact/lib/python3.4/site-packages/django/core/management/__init__.py", line 338, in execute_from_command_line
    utility.execute()
  File "/var/www/swoptact/lib/python3.4/site-packages/django/core/management/__init__.py", line 330, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/var/www/swoptact/lib/python3.4/site-packages/django/core/management/base.py", line 390, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/var/www/swoptact/lib/python3.4/site-packages/django/core/management/base.py", line 441, in execute
    output = self.handle(*args, **options)
  File "/var/www/swoptact/lib/python3.4/site-packages/django/core/management/commands/syncdb.py", line 25, in handle
    call_command("migrate", **options)
  File "/var/www/swoptact/lib/python3.4/site-packages/django/core/management/__init__.py", line 120, in call_command
    return command.execute(*args, **defaults)
  File "/var/www/swoptact/lib/python3.4/site-packages/django/core/management/base.py", line 441, in execute
    output = self.handle(*args, **options)
  File "/var/www/swoptact/lib/python3.4/site-packages/django/core/management/commands/migrate.py", line 221, in handle
    executor.migrate(targets, plan, fake=fake, fake_initial=fake_initial)
  File "/var/www/swoptact/lib/python3.4/site-packages/django/db/migrations/executor.py", line 110, in migrate
    self.apply_migration(states[migration], migration, fake=fake, fake_initial=fake_initial)
  File "/var/www/swoptact/lib/python3.4/site-packages/django/db/migrations/executor.py", line 147, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/var/www/swoptact/lib/python3.4/site-packages/django/db/migrations/migration.py", line 115, in apply
    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
  File "/var/www/swoptact/lib/python3.4/site-packages/django/db/migrations/operations/fields.py", line 201, in database_forwards
    schema_editor.alter_field(from_model, from_field, to_field)
  File "/var/www/swoptact/lib/python3.4/site-packages/django/db/backends/base/schema.py", line 484, in alter_field
    old_db_params, new_db_params, strict)
  File "/var/www/swoptact/lib/python3.4/site-packages/django/db/backends/base/schema.py", line 641, in _alter_field
    params,
  File "/var/www/swoptact/lib/python3.4/site-packages/django/db/backends/base/schema.py", line 111, in execute
    cursor.execute(sql, params)
  File "/var/www/swoptact/lib/python3.4/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/var/www/swoptact/lib/python3.4/site-packages/django/db/utils.py", line 97, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/var/www/swoptact/lib/python3.4/site-packages/django/utils/six.py", line 658, in reraise
    raise value.with_traceback(tb)
  File "/var/www/swoptact/lib/python3.4/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
django.db.utils.ProgrammingError: column "address_id" cannot be cast automatically to type integer
HINT:  Specify a USING expression to perform the conversion.
```

No one else has been able to reproduce this, it seems like this could be specific to postgres as this is what the debian system I was using is setup to use. It seems that the migration that is causing it is: https://github.com/OpenTechStrategies/swoptact/blob/master/swoptact/migrations/0025_auto_20150424_1026.py which is auto-generated by django so this makes this issue even more strange.

**Comment by xray7224** [comment]
This has been fixed in the last commit, it was easier to just remove the migrations which caused this change, it won't effect anything as we had a migration to convert a field to a CharField and then from the CharField back to a Integer foreignkey. The error seems to occur because PostgreSQL doesn't know how to deal with migrating a CharField to integer (as it makes no sense). I suspect this is a Django bug as it created this migration.
